const properties = [
  {
    ref: 0,
    address: "Bellavista, 5",
    population: 0,
    transaction: 0,
    m2: 200,
    heating: 1,
    furnished: 1,
    price: 5000,
    outstanding: 1,
    type: 4,
    description: "Hi I'm a description",
    postalCode: "07701",
    img: ["property1"],
    title: 'MAGNIFICENT VILLA ON THE COAST'
  },
  {
    ref: 1,
    address: "de ses Moreres, 13",
    population: 0,
    transaction: 1,
    m2: 200,
    heating: 1,
    furnished: 1,
    price: 25000,
    outstanding: 1,
    type: 0,
    description: "Hi I'm a description",
    postalCode: "07701",
    img: ["property2"],
    title: 'MAGNIFICENT HOUSE ON THE COAST'
  },
  {
    ref: 2,
    address: "Sant Manuel, 112",
    population: 0,
    transaction: 0,
    m2: 200,
    heating: 1,
    furnished: 1,
    price: 5000,
    outstanding: 0,
    type: 2,
    description: "Hi I'm a description",
    postalCode: "07701",
    img: ["property3"],
    title: 'MAGNIFICENT GARAGE '
  },
  {
    ref: 3,
    address: "Sant Manuel, 112",
    population: 0,
    transaction: 0,
    m2: 200,
    heating: 1,
    furnished: 1,
    price: 5000,
    outstanding: 0,
    type: 3,
    description: "Hi I'm a description",
    postalCode: "07701",
    img: ["property3"],
    title: 'MAGNIFICENT RUSTIC HOUSE'
  },
  {
    ref: 4,
    address: "Sant Manuel, 112",
    population: 0,
    transaction: 0,
    m2: 200,
    heating: 1,
    furnished: 1,
    price: 5000,
    outstanding: 0,
    type: 4,
    description: "Hi I'm a description",
    postalCode: "07701",
    img: ["property3"],
    title: 'MAGNIFICENT VILLA'
  },
  {
    ref: 5,
    address: "Sant Manuel, 112",
    population: 0,
    transaction: 0,
    m2: 200,
    heating: 1,
    furnished: 1,
    price: 5000,
    outstanding: 0,
    type: 0,
    description: "Hi I'm a description",
    postalCode: "07701",
    img: ["property3"],
    title: 'MAGNIFICENT HOUSE'
  },
  {
    ref: 6,
    address: "Sant Manuel, 112",
    population: 0,
    transaction: 0,
    m2: 200,
    heating: 1,
    furnished: 1,
    price: 5000,
    outstanding: 0,
    type: 2,
    description: "Hi I'm a description",
    postalCode: "07701",
    img: ["property3"],
    title: 'MAGNIFICENT GARAGE'
  },
  {
    ref: 7,
    address: "Sant Manuel, 112",
    population: 0,
    transaction: 0,
    m2: 200,
    heating: 1,
    furnished: 1,
    price: 5000,
    outstanding: 0,
    type: 1,
    description: "Hi I'm a description",
    postalCode: "07701",
    img: ["property3"],
    title: 'MAGNIFICENT APARTMENT'
  },
  {
    ref: 8,
    address: "Sant Manuel, 112",
    population: 0,
    transaction: 0,
    m2: 200,
    heating: 1,
    furnished: 1,
    price: 5000,
    outstanding: 0,
    type: 1,
    description: "Hi I'm a description",
    postalCode: "07701",
    img: ["property3"],
    title: 'MAGNIFICENT APARTMENT'
  },
  {
    ref: 9,
    address: "Sant Manuel, 112",
    population: 0,
    transaction: 0,
    m2: 200,
    heating: 1,
    furnished: 1,
    price: 5000,
    outstanding: 0,
    type: 4,
    description: "Hi I'm a description",
    postalCode: "07701",
    img: ["property3"],
    title: 'MAGNIFICENT VILLA'
  }
];